### ISSUE TITLE
xmpp2

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp#293]
So we want to modernize and modularize node-xmpp here is the roadmap.

Server is left out on purpose for the time being.

# Roadmap
- [x] switch to [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md)
  - [x] node-xmpp [PR](https://github.com/node-xmpp/node-xmpp/pull/292)
  - [x] node-xmpp-core [PR](https://github.com/node-xmpp/node-xmpp/pull/294)
  - [x] node-xmpp-server [PR](https://github.com/node-xmpp/node-xmpp/pull/295)
  - [x] node-xmpp-component [PR](https://github.com/node-xmpp/node-xmpp/pull/296) [PR](https://github.com/node-xmpp/node-xmpp/pull/302)
  - [x] node-xmpp-client [PR](https://github.com/node-xmpp/node-xmpp/pull/298) [PR](https://github.com/node-xmpp/node-xmpp/pull/301) [PR](https://github.com/node-xmpp/node-xmpp/pull/300)
  - [x] node-xmpp-jid [PR](https://github.com/node-xmpp/node-xmpp/pull/311)
  - [x] node-xmpp-stanza [PR](https://github.com/node-xmpp/node-xmpp/pull/310)
  - [x] update `README.md`, `package.json`s, links [PR](https://github.com/node-xmpp/node-xmpp/pull/308)
- [x] Move every independent pieces to different packages something like
  - [x] client
    - [x] @xmpp/client-bosh
    - [x] @xmpp/client-tcp
    - [x] @xmpp/client-connection
    - [x] @xmpp/client-websocket
    - [x] FIXME what about auth?
  - [x] @xmpp/component
  - [x] core
    - [x] @xmpp/connection
    - [x] @xmpp/streamparser
- [x] Define and implement a **simple/basic** 'plugin' mechanism (catch in/out stanzas)
- [x] Move non standard features to plugin packages for example
  - @xmpp/plugin-register https://xmpp.org/extensions/xep-0077.html
  - @xmpp/plugin-session https://tools.ietf.org/html/draft-cridland-xmpp-session-01
  - ...
- [x] Publish `@xmpp` modules
- [ ] Deprecated node-xmpp modules
- [ ] Rename github.com/node-xmpp github.com/xmpp2.js or something
- [ ] ...
### meta
- [x] es2015
- [x] code review (remove code smell and the like)
- [ ] doc
- [x] promises
- [x] use https://github.com/jaredhanson/js-sasl
- [x] stop using node-xmpp-tls-connect [PR](https://github.com/node-xmpp/node-xmpp/pull/299)
### client
- [x] replace faye-websocket with ws [PR](https://github.com/node-xmpp/node-xmpp/pull/305)
- [x] re-enable WebSocket client integration tests
- [x] fix skipped integration tests [a](https://github.com/node-xmpp/node-xmpp/pull/303) [b](https://github.com/node-xmpp/node-xmpp/pull/307)
- [x] reduce bundle size (rollup?)
- [x] re-enable client browser tests [PR](https://github.com/node-xmpp/node-xmpp/pull/303) [PR](https://github.com/node-xmpp/node-xmpp/pull/306)
- [x] add client websocket browser tests
- [x] replace request/browser-request; those are way too big for our needs and browser-request is now unsupported 
### tests
- [x] more unit/integration tests
- [x] stop using port 5222
- [x] use a config file rather than hardcoded localhost
- [x] refactor unit/integration tests
- [x] faster travis builds (sudo: false, caching, ...)

**Comment by sonnyp** [comment]
To Do:

* [ ] Documentation
* [ ] More tests
* [ ] BOSH
* [ ] Finalize plugin mechanism

**Comment by sonnyp** [comment]
closing in favor of https://github.com/node-xmpp/node-xmpp/issues/434
